language: 'php'
php:
    - '7.2'
    - '7.3'
    - '7.4'
    - 'nightly'
    - 'hhvm'

matrix:
    allow_failures:
        - php: 'hhvm'
        - php: 'nightly'

install:
    - 'composer install --ignore-platform-reqs'
script:
    - './vendor/bin/phpunit'

sudo: false
