language: php
os: 'linux'

matrix:
    include:
        -   name: '5.6'
            php: '5.6'
        -   name: '7.0'
            php: '7.0'
        -   name: '7.1'
            php: '7.1'
        -   name: '7.2'
            php: '7.2'
        -   name: '7.3'
            php: '7.3'
        -   name: '7.4'
            php: '7.4'
        -   name: '8.0'
            php: '8.0'
    allow_failures:
        -   name: '8.1'
            php: '8.1'

install:
    - composer install --no-interaction --prefer-dist
script:
    - find src/ -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
    - ./vendor/bin/phpunit --bootstrap="tests/bootstrap.php" --test-suffix="Test.php" tests
