language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - 'hhvm'

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer install
    - composer require --dev --prefer-dist doctrine/dbal:^2.3 phpunit/phpunit:^5.7
script:
    - ./vendor/bin/phpunit

sudo: false
