name: "Darsyn IP Automated Tests"

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:

  phpstan:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
      - uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: 'highest'
      - run: 'composer require --dev phpstan/phpstan'
      - run: './vendor/bin/phpstan analyse'

  psalm:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        php:
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
        include:
          - php: '8.2'
            experimental: true
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
      - uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: 'highest'
      - run: 'composer require --dev vimeo/psalm'
      - run: './vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)'
