name: "Darsyn IP Automated Tests"

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:

  psalm:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        php:
          - '8.1'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
      - uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: 'highest'
      - run: 'composer require --dev vimeo/psalm'
      - run: './vendor/bin/psalm --init src 3'
      - run: './vendor/bin/psalm --show-info=false --stats --output-format="github" --threads=$(nproc) --php-version=5.6'
