name: "Static Analysis"

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:

  psalm:
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        php:
          - '8.3'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
      - uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: 'highest'
      # Require vimeo/psalm via command-line instead of adding to Composer's
      # "require-dev"; we only want to run static analysis once on the highest
      # version of PHP available. Also, Psalm on 5.6? No, thank you.
      - run: 'composer require --dev vimeo/psalm'
      - run: './vendor/bin/psalm --config="tests/psalm.xml" --threads="$(nproc)" --php-version="5.6" --no-cache --stats --show-info=false --output-format="github"'

  phpstan:
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        php:
            - '8.3'
    steps:
        - uses: 'actions/checkout@v2'
        - uses: 'shivammathur/setup-php@v2'
          with:
              php-version: '${{ matrix.php }}'
        - uses: 'ramsey/composer-install@v2'
          with:
              dependency-versions: 'highest'
        # Require PHPStan via command-line instead of adding to Composer's
        # "require-dev"; we only want to run static analysis once on the highest
        # version of PHP available.
        - run: 'composer require --dev phpstan/phpstan phpstan/phpstan-deprecation-rules'
        - run: './vendor/bin/phpstan analyze --no-progress --configuration="tests/phpstan.neon" --error-format="github"'
